### ISSUE TITLE
No longer opening files with EC-Lab 11.50

### ISSUE THREAD

**Issue by Smooth203** [vetschn/eclabfiles#12]
I think there were changes with the recent update to eclab that affected other things as well as this library... This is the error I get.
`Traceback (most recent call last):
  File "MY_FILE_PATH/FILE.py", line 44, in <module>
    data, meta = ecf.process(file_path)
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "MY_FILE_PATH/FILE.py", line 75, in process
    return mpr.process(fn, encoding=encoding)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "MY_FILE_PATH/FILE.py", line 686, in process
    settings, params = _process_settings(module_data)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "MY_FILE_PATH/FILE.py", line 504, in _process_settings
    technique, params_dtype = technique_params_dtypes[data[0x0000]]
                              ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 48`

I can still process files made with previous versions of ec lab.
Sorry if there's not enough info -- I can provide

**Comment by Smooth203** [comment]
I see that it's no longer being maintained -- I'll look at YADG
